### ISSUE TITLE
takes a long time at offline stage

### ISSUE THREAD

**Issue by hetolin** [ktgiahieu/PPF-MEAM#5]
Hi, Thank your for sharing your work. I am using your code recently. But when I complied your code and run it. I found that it really takes a long time to finish Offline Model Descriptor  Preparation. And it stuck in the interface as below. Could you please  tell me how long dose it take to finish the offline preparation stage?
<img width="462" alt="截屏2021-07-16 14 04 33" src="https://user-images.githubusercontent.com/37474466/125900045-b5fa529f-b5e3-4f6f-aaa0-cc3edc86b2fa.png">

**Comment by chengm0-0** [comment]
你好，请问你导入stl文件的时候没有报错吗，为什么我一直有错误

**Comment by hetolin** [comment]
我当时跑的时候，导入stl的没有报错，可以正常运行，就是这算法跑的时间有点久

**Comment by chengm0-0** [comment]
我跑代码的时候导入stl后一直报错Segmentation fault (core dumped)，你知道怎么解决吗？万分感谢！
（我从网上下载其他的stl文件导入就不会报错）

**Comment by chengm0-0** [comment]
我现在导入pcd文件，代码可以运行了，不过和你卡在了相同的位置，6个视角提取大约需要多久呢？

**Comment by ktgiahieu** [comment]
About the "stuck in the interface" problem: 
I actually added some std::getchar() function in this demo to perform a step by step tutorial. So if you want everything to run smoothly with no interruption, you may want to remove those lines of code in this file https://github.com/ktgiahieu/PPF-MEAM/blob/master/include/PPF/PPF.cpp

About the "takes a long time at offline stage" problem: 
The intention is that this offline stage should only be ran once and the 
pcl::PointCloud<pcl::PPFSignature>::Ptr **descriptors_PPF**
and the 
pcl::PointCloud<pcl::PointXYZ>::Ptr **model** = pcl::PointCloud<pcl::PointXYZ>::Ptr(new pcl::PointCloud<pcl::PointXYZ>());
should be saved for later use. I think you should save the descriptors_PPF and model and then load them when run in online mode.
I actually have reran the code and it took about 47 seconds. When I use this code in Bin Picking operation, I decrease t_sampling (from PPF.h) from 0.04 to 0.03 to increase accuracy but will takes way much more time (which doesn't affect online stage)
![Screenshot from 2022-03-04 11-20-05](https://user-images.githubusercontent.com/42331617/156698748-ebb24a24-868b-4e31-884c-695db7be5f7d.png)

If you happend to encounter some segmentation fault, do either these following ways: 
- If you want to use VTK to verify results, press Enter AFTER a step is completed, so VTK doesn't crash.
- If you have finished with your detection phase and only care about its pose output in order to be fed into the Bin Picking system (like me http://y2u.be/udqj9vNyUDY), then remove any line of code involving VTK. The project won't render 3D images on VTK and will run way faster.
